### ISSUE TITLE
Extending trait EmbeddedKafka stopped working on update to v5.4.1

### ISSUE THREAD

**Issue by kpmeen** [embeddedkafka/embedded-kafka-schema-registry#108]
I have some custom code that extends `net.manub.embeddedkafka.schemaregistry.EmbeddedKafka` that stopped working after updating to version 5.4.1 of embedded-kafka-schema-registry. The problem is that the overridden function `withRunningServers` uses `scala.reflect.io.Directory` instead of `java.nio.file.Path`.
The problem seems to be fixed in commit e33d1b6003370b81ed45b2492f53385bf0938fa7. I've currently patched this problem locally. But it would be much appreciated if you could publish a patch release to fix the issue (v5.4.1.1).

Thanks 🙂

**Comment by francescopellegrini** [comment]
Hi @kpmeen,
embedded-kafka-schema-registry v5.4.1 is referencing embedded-kafka v2.4.0 which doesn't include embeddedkafka/embedded-kafka/pull/121 yet. That change was released in v2.4.1 and included in embedded-kafka-schema-registry just recently (as you mentioned: embeddedkafka/embedded-kafka-schema-registry/pull/107) but not yet released.

Are you depending on both embedded-kafka v2.4.1 *and* embedded-kafka-schema-registry v.5.4.1? This would bring into scope two different versions of the library and thus causing the issue.

**Comment by kpmeen** [comment]
Thanks for your response @francescopellegrini.

Yes, I rely on both libraries in my particular use-case.

Isn't it a bit premature to release v5.4.1 without also upgrading the upstream dependency version it relies on? Wouldn't it be better to ensure the two versions are aligned? 🤔

**Comment by francescopellegrini** [comment]
May I ask you why are you depending also on embedded-kafka when you already include this library (which itself includes the former)?

To answer your question, Confluent Platform v5.4.1 does not depend on Apache Kafka v2.4.1, but on the previous version instead, so I usually follow step by step their release plan; if I were to release v5.4.1 with Kafka v2.4.1 as a dependency, I'd not be fully compliant with what Confluent offers as packages. I hope this clarifies the situation. :)

**Comment by kpmeen** [comment]
Actually, I asked Confluent about this and Confluent Platform v5.4.1 _does_ depend on Apache Kafka v2.4.1. There is a typo / bug in the release notes of v5.4.1 stating that it uses v.2.4.0. However all of the libraries that depend on Kafka, depend on v2.4.1 in the v5.4.1. release.
The release versioning typically always follows the minor and patch versions of the Apache project.

**Comment by francescopellegrini** [comment]
Maven states that Confluent artifacts depend on v5.4.1-ccs, which I'm not sure what means in terms of Apache Kafka versions..
I just asked on Confluent official Slack channel, I'll let you know when I get a reply.

**Comment by francescopellegrini** [comment]
@kpmeen unfortunately the folks at Confluent didn't provide a thorough explanation, but I guess releasing a patch for the current version is no big deal. =)
Coming out soon.

**Comment by francescopellegrini** [comment]
Ready: https://github.com/embeddedkafka/embedded-kafka-schema-registry/releases/tag/v5.4.1.1
