### ISSUE TITLE
Expose custom properties for schema registry

### ISSUE THREAD

**Issue by xelnaga** [embeddedkafka/embedded-kafka-schema-registry#124]
The call to startSchemaRegistry() within the EmbeddedKafka object does not provide a way of passing custom config to the schema registry server.

Perhaps a customSchemaRegistryProperties could be added to the config and passed through here?

**Comment by andyjayne** [comment]
A practical use case for this would be passing a larger value for KAFKASTORE_TIMEOUT_CONFIG to prevent schema registry timeouts in integration tests.

**Comment by francescopellegrini** [comment]
Hi, I'm currently working on the next refactor of [SchemaRegistryOps](url) which is actually going to be in the direction you both mentioned. :)

**Comment by andyjayne** [comment]
Cool, looks like that would solve it. Thanks.

**Comment by francescopellegrini** [comment]
Included in v5.5.0
