### ISSUE TITLE
log level for embedded kafka

### ISSUE THREAD

**Issue by ChengGit** [embeddedkafka/embedded-kafka-schema-registry#17]
Hi guys,
May I know if there is a way to set default log level for embedded kafka instance? 
I am doing a property based check, and it actually generates too many lines of [info] log to show on travis, so wondering if there is a finer-ground control for kafka log level? Or should I just set a higher log level for all tests? 

Thanks for your time!

**Comment by francescopellegrini** [comment]
Hi @ChengGit, what libraries are you using to control log levels on your app? Kafka relies on `log4j`, but usually in my apps I include `log4j-over-slf4j` to redirect output and have a single knob to control log levels.
Else you'll have to create a `log4j.properties` file for Kafka, as we did in this very project to control tests output.

**Comment by ChengGit** [comment]
thanks! @francescopellegrini  it is muted now after adding a `log4j.properties`

I was using `logback` as logger backend and a bridge library to redirect logs to `logback`. 

However I realise there is a `log4j` backend  packaged within either `kafka` or `embeddedKafka`, and some of kafka logs will always go with `log4j` backend even if I set my `logback.xml` root log level as `ERROR`.

But adding a `log4j.properties`  with `root.logger.level=error`, instead of a `logback.xml`, mute them all.

I am kind of new to java/scala/logging systems, please correct me if I misunderstood anything!

Thanks again for your help!!
