### ISSUE TITLE
how to access the schema registry server in test?

### ISSUE THREAD

**Issue by student2028** [embeddedkafka/embedded-kafka-schema-registry#171]
there is a error:Caused by: java.lang.IllegalArgumentException: Login module not specified in JAAS config
how can I set these info for the schemaRegistry?
thanks
like producer.kafka.sasl.jaas.config="org.apache.kafka.common.security.plain.PlainLoginModule required username=\"USERNAME\" password=\"PASSWORD\";"

**Comment by francescopellegrini** [comment]
Hi @student2028, you can provide additional properties to broker, producer, consumer, and Schema Registry via [EmbeddedKafkaConfig](https://github.com/embeddedkafka/embedded-kafka-schema-registry/blob/8efaad80268f590c5080ed328b74536ab2646a30/embedded-kafka-schema-registry/src/main/scala/net.manub.embeddedkafka/schemaregistry/config.scala#L16).
