### ISSUE TITLE
Custom Schema Registry Port not working

### ISSUE THREAD

**Issue by tharunrajguptayada** [embeddedkafka/embedded-kafka-schema-registry#278]
Not Able To Change the Schema registry Url port

**Comment by francescopellegrini** [comment]
Hi @tharunrajguptayada , there is [a test for this scenario](https://github.com/embeddedkafka/embedded-kafka-schema-registry/blob/master/embedded-kafka-schema-registry/src/test/scala/io/github/embeddedkafka/schemaregistry/EmbeddedKafkaObjectSpec.scala#L50): could you take a look at that and compare it to your code?

**Comment by tharunrajguptayada** [comment]
yeah, thanks solved, the port problem is at the avro serialisation config
