### ISSUE TITLE
support for withRunningKafkaOnFoundPort

### ISSUE THREAD

**Issue by bassmake** [embeddedkafka/embedded-kafka-schema-registry#28]
At the moment it looks like only `withRunningKafka` is supported.

`withRunningKafkaOnFoundPort` with actual config should be supported too.

**Comment by francescopellegrini** [comment]
Hi,
it already is, actually: take a look at [this test](https://github.com/embeddedkafka/embedded-kafka-schema-registry/blob/master/src/test/scala/net/manub/embeddedkafka/schemaregistry/EmbeddedKafkaTraitSpec.scala#L18).

**Comment by bassmake** [comment]
thanks @francescopellegrini ,
my bad, I have no idea how I missed that.
