### ISSUE TITLE
Not able to start the kafka broker

### ISSUE THREAD

**Issue by tharunrajguptayada** [embeddedkafka/embedded-kafka-schema-registry#293]
i am not getting the error with Embeddded Kafka repo , but i need schema registry too :

ERROR kafka.server.BrokerMetadataCheckpoint - Failed to write meta.properties due to
java.nio.file.AccessDeniedException: C:\Users\AVTUMX~1\AppData\Local\Temp\kafka-logs1790594500627329176
at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:115)
at java.nio.channels.FileChannel.open(FileChannel.java:287)
at java.nio.channels.FileChannel.open(FileChannel.java:335)
at org.apache.kafka.common.utils.Utils.flushDir(Utils.java:953)
at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:941)
at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:916)
at kafka.server.BrokerMetadataCheckpoint.liftedTree1$1(BrokerMetadataCheckpoint.scala:214)
at kafka.server.BrokerMetadataCheckpoint.write(BrokerMetadataCheckpoint.scala:204)
at kafka.server.KafkaServer.$anonfun$checkpointBrokerMetadata$2(KafkaServer.scala:772)
at kafka.server.KafkaServer.$anonfun$checkpointBrokerMetadata$2$adapted(KafkaServer.scala:770)
at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:924)
at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:923)
at kafka.server.KafkaServer.checkpointBrokerMetadata(KafkaServer.scala:770)
at kafka.server.KafkaServer.startup(KafkaServer.scala:322)
at io.github.embeddedkafka.ops.KafkaOps.startKafka(kafkaOps.scala:53)
at io.github.embeddedkafka.ops.KafkaOps.startKafka$(kafkaOps.scala:26)
at io.github.embeddedkafka.schemaregistry.EmbeddedKafka$.startKafka(EmbeddedKafka.scala:65)
at io.github.embeddedkafka.schemaregistry.EmbeddedKafka$.start(EmbeddedKafka.scala:83)

**Comment by francescopellegrini** [comment]
Hi @tharunrajguptayada, could you please provide a snippet of your code?

**Comment by tharunrajguptayada** [comment]
yeah sure , i am attaching my code below
`class AvroMockTesting extends AnyWordSpecLike with Matchers with BeforeAndAfterAll {

  val schema: Schema = new Schema.Parser().parse("{\n     \"type\": \"record\",\n    // \"namespace\": \"com.example\",\n     \"name\": \"Customer\",\n     \"version\": \"1\",\n     \"fields\": [\n       { \"name\": \"first_name\", \"type\": \"string\", \"doc\": \"First Name of Customer\" },\n       { \"name\": \"automated_email\", \"type\": \"boolean\", \"default\": true, \"doc\": \"Field indicating if the user is enrolled in marketing emails\" }\n     ]\n}")

  implicit val config:EmbeddedKafkaConfig = EmbeddedKafkaConfig(
    kafkaPort = 9092, schemaRegistryPort = 8081)

  override def beforeAll(): Unit = {
    super.beforeAll()
    EmbeddedKafka.start()
  }

  override def afterAll(): Unit = {
    EmbeddedKafka.stop()
    super.afterAll()
  }

  "runs with embedded kafka and Schema Registry" should {

    implicit val serializer: Serializer[GenericRecord] = {
      val props = Map(
        AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG -> "http://localhost:8081"
      )
      val ser = new KafkaAvroSerializer
      ser.configure(props.asJava, false)
      ser.asInstanceOf[Serializer[GenericRecord]]
    }

    implicit val deSerializer: Deserializer[GenericRecord] = {
      val props = Map(
        AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG -> "http://localhost:8081"
      )
      val ser = new KafkaAvroDeserializer()
      ser.configure(props.asJava, false)
      ser.asInstanceOf[Deserializer[GenericRecord]]
    }
    val topic ="input_topic"


    "work" in {
      val record: GenericRecord = new GenericData.Record(schema)
      record.put("first_name", "yada")
      record.put("automated_email", false)
      EmbeddedKafka.withProducer[String,GenericRecord,Unit]( producer => {
        producer.send(new ProducerRecord[String,GenericRecord](topic,"abc",record))
        producer.flush()
      })

      val listOfTopics = Collections.singletonList(topic)
      EmbeddedKafka.withConsumer[String,GenericRecord,Unit](consumer => {
        consumer.subscribe(listOfTopics)
        var i = 10
        while(i>=0)
          {
            val records = consumer.poll(Duration.ofMillis(1000L))
            records.forEach(record => println("consumed message:" + record.key() +", " + record.value()))
            i-=1
          }
      })

    }
  }

}`

**Comment by francescopellegrini** [comment]
I just tried running your code and it works for me... here it is, reformatted and with the imports I used.

```scala
import io.confluent.kafka.serializers.{
  AbstractKafkaSchemaSerDeConfig,
  KafkaAvroDeserializer,
  KafkaAvroSerializer
}
import io.github.embeddedkafka.Codecs._
import org.apache.avro.Schema
import org.apache.avro.generic.{GenericData, GenericRecord}
import org.apache.kafka.clients.producer.ProducerRecord
import org.apache.kafka.common.serialization.{Deserializer, Serializer}
import org.scalatest.BeforeAndAfterAll
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpecLike

import java.time.Duration
import java.util.Collections
import scala.jdk.CollectionConverters._

class AvroMockTesting extends AnyWordSpecLike with Matchers with BeforeAndAfterAll {

  val schema: Schema = new Schema.Parser().parse(
    """{ "type": "record", "namespace": "com.example", "name": "Customer", "version": "1", "fields": [ { "name": "first_name", "type": "string", "doc": "First Name of Customer" }, { "name": "automated_email", "type": "boolean", "default": true, "doc": "Field indicating if the user is enrolled in marketing emails" } ]}"""
  )

  implicit val config: EmbeddedKafkaConfig =
    EmbeddedKafkaConfig(kafkaPort = 9092, schemaRegistryPort = 8081)

  override def beforeAll(): Unit = {
    super.beforeAll()
    EmbeddedKafka.start()
  }

  override def afterAll(): Unit = {
    EmbeddedKafka.stop()
    super.afterAll()
  }

  "runs with embedded kafka and Schema Registry" should {

    implicit val serializer: Serializer[GenericRecord] = {
      val props = Map(
        AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG -> "http://localhost:8081"
      )
      val ser = new KafkaAvroSerializer
      ser.configure(props.asJava, false)
      ser.asInstanceOf[Serializer[GenericRecord]]
    }

    implicit val deSerializer: Deserializer[GenericRecord] = {
      val props = Map(
        AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG -> "http://localhost:8081"
      )
      val ser = new KafkaAvroDeserializer()
      ser.configure(props.asJava, false)
      ser.asInstanceOf[Deserializer[GenericRecord]]
    }
    val topic = "input_topic"

    "work" in {
      val record: GenericRecord = new GenericData.Record(schema)
      record.put("first_name", "yada")
      record.put("automated_email", false)
      EmbeddedKafka.withProducer[String, GenericRecord, Unit](producer => {
        producer.send(
          new ProducerRecord[String, GenericRecord](topic, "abc", record)
        )
        producer.flush()
      })

      val listOfTopics = Collections.singletonList(topic)
      EmbeddedKafka.withConsumer[String, GenericRecord, Unit](consumer => {
        consumer.subscribe(listOfTopics)
        var i = 10
        while (i >= 0) {
          val records = consumer.poll(Duration.ofMillis(1000L))
          records.forEach(record =>
            println("consumed message:" + record.key() + ", " + record.value())
          )
          i -= 1
        }
      })

    }
  }

}
```

**Comment by tharunrajguptayada** [comment]
import io.github.embeddedkafka.schemaregistry.EmbeddedKafkaConfig
import io.github.embeddedkafka.schemaregistry.EmbeddedKafka

I have tried with these imports , but still getting the same error, may be i will try with another windows machine and check.

Thanks for your response sir
