### ISSUE TITLE
Proposal: drop the WithSchemaRegistry suffix

### ISSUE THREAD

**Issue by francescopellegrini** [embeddedkafka/embedded-kafka-schema-registry#3]
I suggested this [before](https://github.com/manub/scalatest-embedded-kafka/pull/134#discussion_r186494435), but now that the code is isolated in its own project, I'd like to get back to it because I think it's a nice to have.

Notable examples: [Reactive Kafka scaladsl vs javadsl](https://doc.akka.io/docs/akka-stream-kafka/current/home.html#scaladsl-and-javadsl), [Akka Stream scaladsl vs javadsl](https://github.com/akka/akka/tree/master/akka-stream/src/main), [Scala collection mutable vs immutable](https://www.scala-lang.org/api/2.12.4/scala/collection/index.html), [Akka Typed vs un-typed actors](https://doc.akka.io/docs/akka/current/typed/coexisting.html).

**Comment by manub** [comment]
Would it be possible for people wanting to run tests both with or without the schema registry when importing this library?

**Comment by francescopellegrini** [comment]
Yes, as long as they extend the original `net.manub.embeddedkafka.EmbeddedKafka` trait instead of the one in `net.manub.embeddedkafka.schemaregistry`.
It's the same of using both typed and un-typed actors in Akka.

**Comment by manub** [comment]
I'm fine then

**Comment by francescopellegrini** [comment]
Very well, I'll push a PR with the required changes before publishing the 5.1.0 release.
