### ISSUE TITLE
Enable Basic and Bearer REST authentication

### ISSUE THREAD

**Issue by azhur** [embeddedkafka/embedded-kafka-schema-registry#339]
Currently seems not possible to do that unless I miss something.

[SchemaRegistryRestApplication](https://github.com/confluentinc/rest-utils/blob/v7.3.0-662/core/src/main/java/io/confluent/rest/Application.java#L542-L544) uses JAAS which is configured via `-Djava.security.auth.login.config=sample_jaas.config` JVM property. As I understand this property could not be simply enabled globally but should be enabled only for the SchemaRegistryRestApplication code so it should run in a separate JVM.

One way to make it work is to provide a modified SchemaRegistryRestApplication that overrides `createLoginService` method so it returns some fake LoginService that could be configured by the library users.

Probably there is an easier or more elegant way to do that, or simply not to enable REST authentication at all, so feel free to be engaged in the discussion.

**Comment by francescopellegrini** [comment]
Hi @azhur ,
thank you for your contribution!

If what you're looking for is an integration test for client authentication, I'm not really sold on overriding `SchemaRegistryRestApplication` with a custom class only for the scope of testing.
I think that your use case could be better tested on TestContainer or something similar, where you can set up JAAS the way Confluent intended.
