### ISSUE TITLE
I am not able to run different specs using the same embedded Kafka 

### ISSUE THREAD

**Issue by ecastilla95** [embeddedkafka/embedded-kafka-schema-registry#347]
I have tried all possible permutations of the normal embedded-kafka docs for same-kafka tests
```
  override def beforeAll(): Unit = {
    println(s"EmbeddedKafka.isRunning: ${EmbeddedKafka.isRunning}")
    if (!EmbeddedKafka.isRunning) EmbeddedKafka.start()
    ()
  }
```
But probably it is trying to create an instance of Zookeeper every time I call the companion object methods
```
[info] *****.KafkaIngressProducerSpec *** ABORTED ***
[info]   java.net.BindException: Address already in use
[info]   at java.base/sun.nio.ch.Net.bind0(Native Method)
[info]   at java.base/sun.nio.ch.Net.bind(Net.java:555)
[info]   at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
[info]   at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
[info]   at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
[info]   at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:81)
[info]   at org.apache.zookeeper.server.NIOServerCnxnFactory.configure(NIOServerCnxnFactory.java:687)
[info]   at org.apache.zookeeper.server.ServerCnxnFactory.configure(ServerCnxnFactory.java:76)
[info]   at io.github.embeddedkafka.ops.ZooKeeperOps.startZooKeeper(zooKeeperOps.scala:26)
[info]   at io.github.embeddedkafka.ops.ZooKeeperOps.startZooKeeper$(zooKeeperOps.scala:13)
[info]   ...

```

**Comment by francescopellegrini** [comment]
Hi @ecastilla95 , just to make sure, are you importing `EmbeddedKafka` class from the `io.github.embeddedkafka.schemaregistry` package?

**Comment by francescopellegrini** [comment]
[We have a test](https://github.com/embeddedkafka/embedded-kafka-schema-registry/blob/bb3859c068614fe20ff841e4f6c642ec2dee72fe/embedded-kafka-schema-registry/src/test/scala/io/github/embeddedkafka/schemaregistry/EmbeddedKafkaSpec.scala) which looks exactly like what you described, try and see if your code is any different.

**Comment by ecastilla95** [comment]
I see that you are creating different configs in different tests:
[here](https://github.com/embeddedkafka/embedded-kafka-schema-registry/blob/bb3859c068614fe20ff841e4f6c642ec2dee72fe/embedded-kafka-schema-registry/src/test/scala/io/github/embeddedkafka/schemaregistry/EmbeddedKafkaSpec.scala)
[and here](https://github.com/embeddedkafka/embedded-kafka-schema-registry/blob/bb3859c068614fe20ff841e4f6c642ec2dee72fe/embedded-kafka-schema-registry/src/test/scala/io/github/embeddedkafka/schemaregistry/EmbeddedKafkaObjectSpec.scala)

my question is, can we re-use the embedded kafka default config? (in an out-of-the-box style)

I guess it is kind of a non-issue since I can maybe extend a trait but I find it counter intuitive that we have to create it again and again but with different ports

**Comment by ecastilla95** [comment]
Never mind, I have tried both creating a trait and an object, the first test class works perfectly but the second one fails due to the cluster stopping

**Comment by francescopellegrini** [comment]
> can we re-use the embedded kafka default config?

You mean separate files? As long as they are not run concurrently, yes, since each one will start and stop the whole setup every time.
