### ISSUE TITLE
Release 7.3.0 version?

### ISSUE THREAD

**Issue by guizmaii** [embeddedkafka/embedded-kafka-schema-registry#365]
Hi @francescopellegrini,

Would it be possible for you to release a new version, please? 

The update to v7.3.0 of the SR has been made in this commit https://github.com/embeddedkafka/embedded-kafka-schema-registry/commit/563c78179e8d3f9f4434d199e2eebe3959e2884c on the 8th of November.

Cheers,
Jules

**Comment by francescopellegrini** [comment]
Closed by a065f1881d4d6e6c226f89b60b36e2018f0abae0
