### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by Dichotomia** [embeddedkafka/embedded-kafka-schema-registry#386]
Hi,

Would it be possible for you to release a new version, please?

I am interested in this commit https://github.com/embeddedkafka/embedded-kafka-schema-registry/commit/1175d2aca3126fae394a3354ed80a2da7b5bd973 Upgrade to embeddedkafka 3.4.0.

Cheers

**Comment by francescopellegrini** [comment]
Hi @Dichotomia ,
I'm waiting for the next release from Confluent, since v7.4 will be the version supporting Kafka v3.4

**Comment by francescopellegrini** [comment]
Fixed by df51ced6a49fd15b7ea3642f8d05c1931e3da263

**Comment by Dichotomia** [comment]
Thanks!
