### ISSUE TITLE
Version 7.6.1 uses scala 3.4.1

### ISSUE THREAD

**Issue by Dichotomia** [embeddedkafka/embedded-kafka-schema-registry#465]
Hi,

This library uses scala 3.4.1.
It should be good to keep scala 3.3.X because it is the LTS as preconised here for example.

https://www.scala-lang.org/blog/2022/08/17/long-term-compatibility-plans.html

**Comment by guizmaii** [comment]
@Dichotomia Can you make a PR to fix this issue, please?

**Comment by Dichotomia** [comment]
Hi. There is the pull request https://github.com/embeddedkafka/embedded-kafka-schema-registry/pull/466

**Comment by guizmaii** [comment]
Thanks for your contribution @Dichotomia!

I published a new version https://github.com/embeddedkafka/embedded-kafka-schema-registry/releases/tag/v7.6.1.1
Should be available in a few hours in Maven Central
