### ISSUE TITLE
Build for Scala 2.13

### ISSUE THREAD

**Issue by Reeebuuk** [embeddedkafka/embedded-kafka-schema-registry#78]
Hi guys :)

Is it possible to get a build for 2.13 as well?

EDIT: I see it's blocked by Confluent, is there a ticket opened on their side?

**Comment by Reeebuuk** [comment]
https://www.confluent.io/blog/apache-kafka-2-4-latest-version-updates/

Great timing :)

**Comment by francescopellegrini** [comment]
Hi @Reeebuuk,
as soon as Confluent 5.4.0 artifacts will be publicly available, a new release will be pushed. :)

**Comment by francescopellegrini** [comment]
Looks like our folks at Confluent didn't port Kafka support to 2.13 in their latest release, unfortunately: https://docs.confluent.io/5.4.0/installation/versions-interoperability.html#scala :(

**Comment by otobrglez** [comment]
Hey guys!

Any news on support for 2.13? I would love to use this thing, but support for 2.13 is a blocker for me. ;/

Cheers!

**Comment by francescopellegrini** [comment]
@otobrglez Please see linked issue on confluent-common repo.
Unfortunately this is out of my control..

**Comment by francescopellegrini** [comment]
Actually, I just tried rebasing an old 2.13 branch I was working on and now it works! In fb7be72 and 2b41a2e we got rid of some transitive dependencies which probably were causing issues, anyway it's great news!
